public class Enum {
    public enum StateNames
    {
        ACCEPTING_REQUEST,ADVANCED,AWAITING_DISK_SPACE,
        AWAITING_INTERNET,AWAITING_NEXT_REQUEST,BEGINNER,
        CHECK_PENDING_DOWNLOAD,DOWNLOADING_REQUEST,DOWNLOAD_PAUSED,
        FIXING_DOWNLOAD,INTERNET_OFF,INTERNET_ON,MOVIE_OFF,MOVIE_ON,
        MOVIE_PAUSED,OFF,ON,PLAYING_MOVIE,PROCESSING_DOWNLOADS,PROCESSING_REQUEST,
        PROFESSIONAL,RECEIVED_REQUEST,RESET_DOWNLOAD,USER_STATUS
    }
    public enum OnRegionNames
    {
        GETTING_REQUESTS,IDENTIFY_INTERNET,MANAGING_REQUESTS,PLAYING_MOVIES, MANEGERING_USER_STATUS
    }
}
